[build]
  command = "yarn build" # the command you run to build this file
  functions = "server"
  publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically